src/ApplicationBundle/Entity/GhAdmin.php
<?php

namespace ApplicationBundle\Entity;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

use Doctrine\ORM\Mapping as ORM;

/**
 * GhAdmin
 *
 * @ORM\Table(name="gh_admin")
 * @ORM\Entity(repositoryClass="ApplicationBundle\Repository\GhAdminRepository")
 * @UniqueEntity(fields="email", message="Email deja existe")
 * @UniqueEntity(fields="cin", message="Cin deja existe")
 */
class GhAdmin implements UserInterface, \Serializable
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string", length=255, unique=true)
     * @Assert\Email()
     * @Assert\NotBlank()
     */
    private $email;

    /**
     * @var string
     *
     * @ORM\Column(name="password", type="string", length=255)
     * @Assert\NotBlank()
     */
    private $password;

    /**
     * @var string
     *
     * @ORM\Column(name="cin", type="string", length=255, unique=true)
     * @Assert\NotBlank()
     */
    private $cin;

    /**
     * @Assert\NotBlank()
     * @Assert\Length(max=4096)
     */
    private $verify_password;

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * Set email
     *
     * @param string $email
     *
     * @return GhAdmin
     */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
     * Get email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set password
     *
     * @param string $password
     *
     * @return GhAdmin
     */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    /**
     * Get password
     *
     * @return string
     */
    public function getPassword()
    {
        return $this->password;
    }

    /**
     * Set cin
     *
     * @param string $cin
     *
     * @return GhAdmin
     */
    public function setCin($cin)
    {
        $this->cin = $cin;

        return $this;
    }

    /**
     * Get cin
     *
     * @return string
     */
    public function getCin()
    {
        return $this->cin;
    }

    public function getVerifyPassword()
    {
        return $this->verify_password;
    }

    public function setVerifyPassword($password)
    {
        $this->verify_password = $password;
    }

    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }

    public function getRoles()
    {
        return array('ROLE_GHADMIN');
    }

    public function eraseCredentials()
    {
    }
    public function getUsername()
    {
        return $this->email;
    }
    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->email,
            $this->password,
            $this->cin
            // see section on salt below
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->email,
            $this->password,
            $this->cin,
            // see section on salt below
            // $this->salt
            ) = unserialize($serialized);
    }
}

src/ApplicationBundle/Entity/Ghouse.php
<?php

namespace ApplicationBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * Ghouse
 *
 * @ORM\Table(name="ghouse")
 * @ORM\Entity(repositoryClass="ApplicationBundle\Repository\GhouseRepository")
 */
class Ghouse implements \Serializable
{
    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="nom", type="string", length=255, unique=true)
     */
    private $nom;

    /**
     * @var string
     *
     * @ORM\Column(name="address", type="string", length=255)
     */
    private $address;

    /**
     * @var string
     *
     * @ORM\Column(name="nomPrenomProp", type="string", length=255)
     */
    private $nomPrenomProp;

    /**
     * @var int
     *
     * @ORM\Column(name="mobileNum", type="integer")
     */
    private $mobileNum;

    /**
     * @var int
     *
     * @ORM\Column(name="homeNum", type="integer")
     */
    private $homeNum;

    /**
     * @var string
     *
     * @ORM\Column(name="aPropos", type="text")
     */
    private $aPropos;

    /**
     * @var string
     *
     * @ORM\Column(name="options", type="text")
     */
    private $options;

    /**
     * @var float
     *
     * @ORM\Column(name="maplng", type="float")
     */
    private $mapLng;

    /**
     * @var float
     *
     * @ORM\Column(name="maplnt", type="float")
     */
    private $mapLat;

    /**
     * @var int
     *
     * @ORM\Column(name="ghadmin_id", type="integer")
     */
    private $ghadmin_id;

    /**
     * @var string
     *
     * @ORM\Column(name="conditions", type="text")
     */
    private $conditions;

    /**
     * @var float
     *
     * @ORM\Column(name="prixNuit", type="float")
     */
    private $prixNuit;

    /**
     * @var string
     *
     * @ORM\Column(name="mots_cles", type="string")
     */
    private $mots_cles;

    /**
     * @var string
     *
     * @ORM\Column(name="email", type="string")
     */
    private $email;

    /**
     * @var int
     *
     * @ORM\Column(name="is_validated", type="integer", options={"default" : 0})
     */
    private $is_validated;

    /**
     * @var int
     *
     * @ORM\Column(name="dateCreated", type="date")
     */
    private $dateCreated;

    public function __construct()
    {
        $this->gh_images = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set nom
     *
     * @param string $nom
     *
     * @return Ghouse
     */
    public function setNom($nom)
    {
        $this->nom = $nom;

        return $this;
    }

    /**
     * Get nom
     *
     * @return string
     */
    public function getNom()
    {
        return $this->nom;
    }

    /**
     * Set address
     *
     * @param string $address
     *
     * @return Ghouse
     */
    public function setAddress($address)
    {
        $this->address = $address;

        return $this;
    }

    /**
     * Get address
     *
     * @return string
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Set nomPrenomProp
     *
     * @param string $nomPrenomProp
     *
     * @return Ghouse
     */
    public function setNomPrenomProp($nomPrenomProp)
    {
        $this->nomPrenomProp = $nomPrenomProp;

        return $this;
    }

    /**
     * Get nomPrenomProp
     *
     * @return string
     */
    public function getNomPrenomProp()
    {
        return $this->nomPrenomProp;
    }

    /**
     * Set mobileNum
     *
     * @param integer $mobileNum
     *
     * @return Ghouse
     */
    public function setMobileNum($mobileNum)
    {
        $this->mobileNum = $mobileNum;

        return $this;
    }

    /**
     * Get mobileNum
     *
     * @return int
     */
    public function getMobileNum()
    {
        return $this->mobileNum;
    }

    /**
     * Set homeNum
     *
     * @param integer $homeNum
     *
     * @return Ghouse
     */
    public function setHomeNum($homeNum)
    {
        $this->homeNum = $homeNum;

        return $this;
    }

    /**
     * Get homeNum
     *
     * @return int
     */
    public function getHomeNum()
    {
        return $this->homeNum;
    }

    /**
     * Set aPropos
     *
     * @param string $aPropos
     *
     * @return Ghouse
     */
    public function setAPropos($aPropos)
    {
        $this->aPropos = $aPropos;

        return $this;
    }

    /**
     * Get aPropos
     *
     * @return string
     */
    public function getAPropos()
    {
        return $this->aPropos;
    }

    /**
     * Set options
     *
     * @param string $options
     *
     * @return Ghouse
     */
    public function setOptions($options)
    {
        $this->options = $options;

        return $this;
    }

    /**
     * Get options
     *
     * @return string
     */
    public function getOptions()
    {
        return $this->options;
    }

    /**
     * Set conditions
     *
     * @param string $conditions
     *
     * @return Ghouse
     */
    public function setConditions($conditions)
    {
        $this->conditions = $conditions;

        return $this;
    }

    /**
     * Get conditions
     *
     * @return string
     */
    public function getConditions()
    {
        return $this->conditions;
    }

    /**
     * Set mapLng
     *
     * @param string $mapLng
     *
     * @return Ghouse
     */
    public function setMapLng($mapLng)
    {
        $this->mapLng = $mapLng;

        return $this;
    }

    /**
     * Get mapLng
     *
     * @return float
     */
    public function getMapLng()
    {
        return $this->mapLng;
    }

    /**
     * Set mapLat
     *
     * @param string $mapLat
     *
     * @return Ghouse
     */
    public function setMapLat($mapLat)
    {
        $this->mapLat = $mapLat;

        return $this;
    }

    /**
     * Get mapLat
     *
     * @return float
     */
    public function getMapLat()
    {
        return $this->mapLat;
    }

    /**
     * Set prixNuit
     *
     * @param float $prixNuit
     *
     * @return Ghouse
     */
    public function setPrixNuit($prixNuit)
    {
        $this->prixNuit = $prixNuit;

        return $this;
    }

    /**
     * Get prixNuit
     *
     * @return float
     */
    public function getPrixNuit()
    {
        return $this->prixNuit;
    }

    /**
     * Set GhouseAdmin
     *
     * @param float $GhouseAdmin
     *
     * @return Ghouse
     */
    public function setGhouseAdmin($GhouseAdmin)
    {
        $this->ghadmin_id = $GhouseAdmin;

        return $this;
    }

    /**
     * Get GhouseAdmin
     *
     * @return int
     */
    public function getGhouseAdmin()
    {
        return $this->ghadmin_id;
    }

    /**
     * Set MotsCles
     *
     * @param string $MotsCles
     *
     * @return Ghouse
     */
    public function setMotsCles($MotsCles)
    {
        $this->mots_cles = $MotsCles;

        return $this;
    }

    /**
     * Get Email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     * Set Email
     *
     * @param string $Email
     *
     * @return Ghouse
     */
    public function setEmail($Email)
    {
        $this->email = $Email;

        return $this;
    }

    /**
     * Get MotsCles
     *
     * @return string
     */
    public function getMotsCles()
    {
        return $this->mots_cles;
    }

    /**
     * Set IsValidated
     *
     * @param int $IsValidated
     *
     * @return Ghouse
     */
    public function setIsValidated($IsValidated)
    {
        $this->is_validated = $IsValidated;

        return $this;
    }

    /**
     * Get IsValidated
     *
     * @return int
     */
    public function getIsValidated()
    {
        return $this->is_validated;
    }

    public function getRoles()
    {
        return array('ROLE_GHOUSE');
    }

    /**
     * @Assert\Type(type="ApplicationBundle\Entity\GhouseImages")
     * Un maison a beaucoup des images.
     * @ORM\OneToMany(targetEntity="GhouseImages", mappedBy="ghouseId", cascade={"persist", "remove" })
     */
    protected $gh_images;


    public function getGhImages()
    {
        return $this->gh_images;
    }

    public function setGhImages(GhouseImages $gh_images)
    {
        $this->gh_images->add($gh_images);
        return $this;
    }

    /**
     * Set DateCreated
     *
     * @param None
     *
     * @return Ghouse
     */
    public function setDateCreated()
    {
        $this->dateCreated = new \DateTime("now");
        return $this;
    }

    /**
     * Get DateCreates
     *
     * @return DateTime
     */
    public function getDateCreated()
    {
        return $this->dateCreated;
    }

    public function serialize()
    {
        $images = array();
        foreach ($this->gh_images as $g) {
            $images[] = $g->serialize();
        }
        return array(
            "id" =>
                $this->id,
            "nom" =>
                $this->nom,
            "address" =>
                $this->address,
            "nomPrenomProp" =>
                $this->nomPrenomProp,
            "mobileNum" =>
                $this->mobileNum,
            "homeNum" =>
                $this->homeNum,
            "aPropos" =>
                $this->aPropos,
            "options" =>
                $this->options,
            "mapLng" =>
                $this->mapLng,
            "mapLat" =>
                $this->mapLat,
            "ghadmin_id" =>
                $this->ghadmin_id,
            "conditons" =>
                $this->conditions,
            "prixNuit" =>
                $this->prixNuit,
            "mots_cles" =>
                $this->mots_cles,

src/ApplicationBundle/Resources/views/FrontView/all-ghouse.html.twig
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}GuestHouses-TN | Tout les maisons{% endblock %}</title>
    {% include '@Application/FrontView/header.html.twig' %}

</head>
<body id="bg-main">
{% include '@Application/FrontView/navbar.html.twig' %}

<div class="row mt-5">
</div>
<main class="mt-5">
    <div class="container">
        <div class="row d-flex justify-content-around">
            <div class="col-md-4 col-sm-12">
                <div class="md-form white">
                    <i class="fa fa-search prefix"></i>
                    <input type="text" id="searchInput" onkeyup="searchInput(this)" class="form-control"
                           placeholder="Chercher maison par nom"
                           list="suggestions">
                </div>
            </div>
        </div>
        <datalist id="suggestions">
        </datalist>
        <hr class="my-4">

        <section id="ght-explore-choice">
            <h3 class="mb-0" id="display-10">Explorer GuestHouses:</h3>
            <div class="row">
                <div class="media z-depth-1-half my-4 mr-3">
                    <img src="{{ asset("assets/img/gh-snaps/1.jpg") }}" class="d-flex mr-3 img-fluid rounded-left"
                         width="100"
                         height="100"/>
                    <div class="media-body">
                        <a href="#">
                            <h5 class="mt-3 mr-4">Les Sponsorisées</h5>
                        </a>
                    </div>
                </div>
                <div class="media z-depth-1-half my-4 mr-3">
                    <img src="{{ asset("assets/img/gh-snaps/1.jpg") }}" class="d-flex mr-3 img-fluid rounded-left"
                         width="100"
                         height="100"/>
                    <div class="media-body">
                        <a href="#">
                            <h5 class="mt-3 mr-4">Les Meilleures</h5>
                        </a>
                    </div>
                </div>
                <a href="#">
                    <div class="media z-depth-1-half my-4 mr-3">
                        <img src="{{ asset("assets/img/gh-snaps/1.jpg") }}" class="d-flex mr-3 img-fluid rounded-left"
                             width="100"
                             height="100" href="#"/>
                        <div class="media-body">
                            <h5 class="mt-3 mr-4" id="newer_ghouses">Les Nouvelles</h5>
                        </div>
                    </div>
                </a>
            </div>
        </section>
        <hr class="my-4">
        <section id="ght-explore-present">
            <h3 class="mb-0" id="display-10">Les Maisons presents chez nous :</h3>


            <div class="row mt-4">
                {% for ghouse in ghouses %}
                    <div class="card mr-3 mb-2" style="width:265px;">
                        <!--Card image-->
                        <div class="view overlay hm-white-slight">
                            <img src="{{ asset(ghouse.ghImages[0].getPath()) }}" height="150" width="280" alt="">
                            <a>
                                <div class="mask"></div>
                            </a>
                        </div>
                        <!--/.Card image-->
                        <!--Card content-->
                        <div class="card-body">
                            <!--Social shares button-->
                            <a class="activator"><h5 class="pink-text"><i class="fa fa-cutlery"></i> Culinary</h5><i
                                        class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star"
                                                                                     aria-hidden="true"></i><i
                                        class="fa fa-star" aria-hidden="true"></i><i class="fa fa-star"
                                                                                     aria-hidden="true"></i><i
                                        class="fa fa-star-o" aria-hidden="true"></i></a>

                            <!--Title-->
                            <h4 class="card-title">{{ ghouse.nom }}</h4>
                            <hr>
                            <!--Text-->
                            <p class="card-text ">{{ ghouse.aPropos|length > 50 ? ghouse.aPropos|slice(0, 50) ~ '...' : ghouse.aPropos }}</p>
                            <a href="{{ path('application_ghouse_front', { 'id': ghouse.id }) }}"
                               class="d-flex flex-row-reverse">
                                <h5 class="waves-effect waves-dark p-2">Voir <i class="fa fa-chevron-right"></i></h5>
                            </a>
                        </div>
                    </div>
                    <!--/.Card content-->
                {% endfor %}
                <!-- ici on met des nouvelles lignes des maisons generérs par le click  <div class="row mt-4" id="ght-new-row" style="display: none;"> </div> -->
            </div>
        </section>
        <div class="d-flex justify-content-center mt-4">
            <button class="btn btn-primary d-flex justify-content-center btn-sm" id="load-more"><i
                        class="fa fa-cloud-download" aria-hidden="true"></i></button>
        </div>
    </div>
</main>


{% include '@Application/FrontView/footer.html.twig' %}

<script src="{{ asset('assets/js/all-ghouses.js') }}">
</script>
<script type="text/javascript" src="{{ asset('assets/js/bootstrap-notify.js') }}"></script>
{% for label,message in app.flashes %}
    <script>
        $(document).ready(function () {
            {
                $.notify({
                    title: '<strong>' + '{{ label|upper }}' + '</strong>',
                    message: '{{ message[0] }}'
                }, {
                    offset: {
                        x: 5,
                        y: 70
                    },
                    type: '{{ label }}'
                });
            }
        });
    </script>
{% endfor %}

<script>
    $(document).on('click', '#newer_ghouses', function () {
        $.ajax({
            url: '{{ (path('application_ghouse_all_param')) }}',
            type: "POST",
            dataType: "json",
            data: {
                "critere": "newest"
            },
            async: true,
            success: function (data) {
                console.log(data);
                $('#ght-explore-present').hide();

            }
        });
    });
    function searchInput(data) {
        var suggestions = $('#suggestions');
        if (data.value) {
            $.ajax({
                url: '{{ (path('application_ghouse_all_param')) }}',
                type: "POST",
                dataType: "json",
                data: {
                    "critere": "input",
                    "input": data.value
                },
                async: true,
                success: function (data) {
                    data.forEach(function (item) {
                        var option = document.createElement('option');
                        var link = document.createElement('a');
                        var href = "{{ path('application_ghouse_front', { 'id':  "placeholder" }) }}";
                        href.replace('placeholder', item.id);
                        link.href = href;
                        option.value = item.nom;
                        link.append(option);
                        suggestions.append(link);
                        link.onclick(function () {
                        });
                        console.log(link);
                    });
                },
                error: function (e) {
                    data.placeholder = "Couldn't load datalist options :(";
                },
                beforeSend: function (xhr) {
                    console.log("before sent");
                }
            });
        }
        else {
            suggestions.empty();
        }

    }

</script>

</body>

</html>

src/ApplicationBundle/Resources/views/FrontView/header.html.twig
{% block stylesheets %}
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300|Raleway|Playfair+Display" rel="stylesheet">
    <!-- Bootstrap core CSS -->
    <link href="{{ asset('assets/css/bootstrap.min.css') }}" rel="stylesheet">
    <!-- Material Design Bootstrap -->
    <link href="{{ asset('assets/css/mdb.min.css') }}" rel="stylesheet">
    <!-- Your custom styles (optional) -->
    <link href="{{ asset('assets/css/style.css') }}" rel="stylesheet">
    <!-- Carousel style -->
    <link type="text/css" rel="stylesheet" href="{{ asset('assets/css/lightslider.css') }}"/>
{% endblock %}

src/ApplicationBundle/Resources/views/FrontView/navbar.html.twig
<!--Main Navigation-->
{% block navbar %}
        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar smooth-scroll" id="ght-navbar">
            <div class="container">
                <!-- Navbar brand -->
                <a class="navbar-brand" href="{{ url('application_front_homepage') }}">GuestHouses Tunisia</a>
                <!-- Collapse button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                        data-target="#navbarSupportedContent"
                        aria-controls="navbarSupportedContent" aria-expanded="false"
                        aria-label="Toggle navigation"><span
                            class="navbar-toggler-icon"></span></button>

                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Links -->
                    <ul class="navbar-nav ml-auto">
                        <a href="{{ url('application_ghouse_all') }}">
                            <button class="btn btn-outline-white btn-sm my-0">Trouver une maison d'hotes</button>
                        </a>
                        <a href="contact.html">
                            <button class="btn btn-outline-white btn-sm my-0">Questions fréquentes</button>
                        </a>
                        {% if not is_granted('IS_AUTHENTICATED_FULLY') %}
                            <a href="{{ url('application_propback_login') }}">
                                <button class="btn btn-outline-white btn-sm my-0">Espace pro</button>
                            </a>
                        {% endif %}
                        <div class="dropdown">
                            {% if is_granted('IS_AUTHENTICATED_FULLY') %}
                                {% if is_granted(expression(
                                '"ROLE_GHUSER" in roles'
                                )) %}
                                    <a href="#" class="dropdown-toggle btn btn-outline-white btn-sm my-0"
                                       id="login-user"
                                       data-toggle="dropdown"><b>Espace particulier</b> <span class="caret"></span></a>
                                    <ul id="login-dp" class="dropdown-menu my-2">
                                        <li id="dp-menu">
                                            <a class="dropdown-item"
                                               href="{{ url('application_userback_dashboard', {'id' : app.user.id}) }}">
                                                Profile</a><br>
                                            <a class="dropdown-item" href="#!">Wish list</a>
                                            <a class="dropdown-item"
                                               href="{{ url('application_userback_dashboard', {'id': app.user.id }) }}">Dashboard</a>
                                            <a class="dropdown-item"
                                               href="{{ url('application_userback_dashboard', {'id': app.user.id }) }}">Messages</a>
                                            <div class="dropdown-item" class="dropdown-divider"></div>
                                            <a href="{{ url('application_logout') }}">Se deconnecter</a>
                                        </li>
                                    </ul>
                                {% endif %}
                                {% if is_granted(expression(
                                '"ROLE_GHADMIN" in roles'
                                )) %}
                                    <a href="#" class="dropdown-toggle btn btn-outline-white btn-sm my-0"
                                       id="login-user"
                                       data-toggle="dropdown"><b>Espace Pro</b> <span class="caret"></span></a>
                                    <ul id="login-dp" class="dropdown-menu my-2">
                                        <li id="dp-menu">
                                            <a class="dropdown-item"
                                               href="{{ url('application_propback_maison') }}">
                                                AJOUTER MAISON D'HOTE</a><br>
                                            <a class="dropdown-item"
                                               href="{{ url('application_propback_dashboard') }}">Dashboard</a>
                                            <a class="dropdown-item"
                                               href="{{ url('application_propback_dashboard') }}">Messages</a>
                                            <div class="dropdown-item" class="dropdown-divider"></div>
                                            <a href="{{ url('application_logout') }}">Se deconnecter</a>
                                        </li>
                                    </ul>
                                {% endif %}
                            {% else %}
                                <a href="#" class="dropdown-toggle btn btn-outline-white btn-sm my-0" id="login-user"
                                   data-toggle="dropdown"><b>Espace particulier</b> <span class="caret"></span></a>
                                <ul id="login-dp" class="dropdown-menu my-2">
                                    <li>
                                        <div class="row">
                                            <div class="col-md-12" id="login-dp-from">
                                                {{ form_start(login_form, {'action': url(app.request.attributes.get('_route')), 'attr': { 'class' : 'form' } }) }}
                                                <div class="form-group">
                                                    {{ form_widget(login_form.username, {'attr': { 'class' : 'form-control', 'placeholder' : 'Username' } }) }}
                                                </div>
                                                <div class="form-group">
                                                    {{ form_widget(login_form.password, {'attr': { 'class' : 'form-control', 'placeholder' : 'password'} }) }}
                                                    <div class="help-block text-right"><a href="">Mot de passe oublie
                                                            ?</a></div>
                                                </div>
                                                <div class="form-group">
                                                    <button type="submit" class="btn btn-outline-white btn-block">Se
                                                        connecter
                                                    </button>
                                                </div>
                                                {{ form_end(login_form) }}
                                                <hr class="hr-light">
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-md-12">
                                                <a href="" class="pull-right btn btn-default btn-rounded"
                                                   data-toggle="modal" data-target="#registerform">S'inscrire?</a>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            {% endif %}
                        </div>
                    </ul>
                </div>
                <!-- Collapsible content -->
            </div>
        </nav>
        <!--/.Navbar-->
    <!--Main Navigation-->
{% endblock %}